# Generated by Django 3.2.3 on 2021-06-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pinfornmation',
            name='Age',
            field=models.IntegerField(),

        ),
        migrations.AddField(
            model_name='pinfornmation',
            name='MobileNumber',
            field=models.IntegerField(),

        ),
        migrations.AddField(
            model_name='pinfornmation',
            name='Pin',
            field=models.IntegerField(),

        ),
    ]
